CREATE DATABASE product_db;
CREATE DATABASE order_db;
CREATE DATABASE payment_db;
CREATE DATABASE inventory_db;
CREATE DATABASE notification_db;

GRANT ALL PRIVILEGES ON DATABASE product_db TO admin;
GRANT ALL PRIVILEGES ON DATABASE order_db TO admin;
GRANT ALL PRIVILEGES ON DATABASE payment_db TO admin;
GRANT ALL PRIVILEGES ON DATABASE inventory_db TO admin;
GRANT ALL PRIVILEGES ON DATABASE notification_db TO admin;